modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "LGPL-3.0"

[[mods]]
modId = "noend"
version = "${version}"
displayName = "noend"
authors = "QPCrummer"
description = '''
Easily disable the end and nether with gamerules
'''
#logoFile = ""

[[dependencies.noend]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.noend]]
modId = "minecraft"
type = "required"
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "noend.mixins.json"
